// <auto-generated />
namespace TechShopWebsite.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class DBv15 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DBv15));
        
        string IMigrationMetadata.Id
        {
            get { return "202305091755576_DBv15"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
